### PR TITLE
Making dialog resizable + automagic compiling of ui file

### PR DESCRIPTION
**Pull request by rduivenvoorde**
Hi Marco,

the changes to the ui file are to make the dialog resizable, as all widgets had fixed sizes and positions, making the dialog look funny on other OS's and with other Qt-theme's.

quickprint_140

commit e9f0ace is a trick to be able to redesign the ui without recompiling the ui file everytime. 

upon loading of the dialog in QGIS, the ui file is compiled auto magically

### CODE REVIEW

**Comment by MarcoDuiker** [comment]
Hi Richard,
Thank you.
Unfortunately the plugin doesn't work anymore. The save button can be clicked, but no file is saved. 
There are no error messages in the log pane.

Can you please look into it?

**Comment by rduivenvoorde** [comment]
@MarcoDuiker 

I fixed the button bar, some default connections were not there.

The last commit is to not have the litterals strings 'Title', 'Subtitle' and 'Attributions' in your pdf even if not given.

**Comment by MarcoDuiker** [comment]
Richard,

Thank you for your valuable additions.

Unfortunately I do not agree on the new Attribution/ Remarks set-up.

With almost any map, attribution is necessary. We should promote that as in the original setup. In that setup the user can deviate when necessary (no attribution needed) by altering the Attribution: text in the dialog box.

Furthermore I think your setup is less clear for the end user. The user will think "Huh, why two boxes for remarks?". This will discourage the user from using them and doing proper attribution.

So please revert to the original setup for attribution and remarks.

**Comment by MarcoDuiker** [comment]
Uploaded as version 0.4 to the QGIS plugin repo.

**Pull request merged**
